apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpg-parser-dep
  namespace: ballerina-playground
  labels:
    app: bpg-parser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpg-parser
  template:
    metadata:
      labels:
        app: bpg-parser
    spec:
      containers:
      - name: bpg-parser-container
        imagePullPolicy: Always
        image: gcr.io/${BPG_GCP_PROJECT_ID}/parser:v0.1-20190314-1047
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        ports:
        - name: http-port
          containerPort: 80
        - name: https-port
          containerPort: 8443
        readinessProbe:
          tcpSocket:
            port: http-port
          initialDelaySeconds: 3
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: http-port
          initialDelaySeconds: 5
          periodSeconds: 20