apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpg-launcher-dep
  namespace: ballerina-playground
  labels:
    app: bpg-launcher-1
    appType: bpg-launcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpg-launcher
  template:
    metadata:
      labels:
        app: bpg-launcher
    spec:
      containers:
      - name: bpg-launcher-container
        imagePullPolicy: Always
        image: gcr.io/${BPG_GCP_PROJECT_ID}/launcher:v0.1-20190314-1042
        resources:
          limits:
            cpu: "2"
          requests:
            cpu: "2"
        args:
        - -cpus
        - "2"
        env:
        - name: BPG_REDIS_WRITE_HOST
          value: "redis-master"
        - name: BPG_REDIS_WRITE_PORT
          value: 6379
        - name: BPG_REDIS_READ_HOST
          value: "redis-slave"
        - name: BPG_REDIS_READ_PORT
          value: 6379
        - name: BPG_CACHE_NODE
          value: "false"
        ports:
        - name: http-port
          containerPort: 80
        - name: https-port
          containerPort: 443
        readinessProbe:
          tcpSocket:
            port: https-port
          initialDelaySeconds: 3
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: https-port
          initialDelaySeconds: 5
          periodSeconds: 20
        # volumeMounts:
        # - mountPath: /mnt
        #   name: ballerina-nfs
      # volumes:
      # - name: ballerina-nfs
      #   nfs:
      #     path: /exports
      #     server: NFS_SERVER_IP
