name: Generate ballerina by examples

on: [push, pull_request]

jobs:
  bbe-gen:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.6.2
      env:
        GOPATH: /home/runner/work/ballerina-release

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate BBEs
      run: sh ballerinaByExample/build-bbe.sh v1-2 bbes v1.2.0 true
    - uses: actions/upload-artifact@v1
      with:
        name: bbe-artifact
        path: bbes