name: Notify Notifications chat

on:
  repository_dispatch:
    types: [notify-build-failure, notify-ballerinax-connector-build-failure, notify-trivy-failure]

jobs:
  send-chat-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Install Python packages
        run: |
          pip install cryptography
          pip install httplib2
          pip install PyGithub
          
      - name: Wget required files
        run: |
          python3 dependabot/notify_build_failure.py ${{ github.event.client_payload.repoName }} "${{ github.event.client_payload.workflow }}" ${{ github.event.action }} ${{ github.event.client_payload.branch }}
        env:
          CHAT_ID: ${{ secrets.NOTIFICATIONS_CHAT_ID }}
          CHAT_KEY: ${{ secrets.NOTIFICATIONS_CHAT_KEY }}
          CHAT_TOKEN: ${{ secrets.NOTIFICATIONS_CHAT_TOKEN }}
          ENV_USER_ENCRYPTION_KEY: ${{secrets.USER_ENCRYPTION_KEY}}
          BALLERINA_BOT_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
