name: Notify Notifications chat

on:
  repository_dispatch:
    types: [notify-connector-failure]
  workflow_dispatch:

jobs:
  send-chat-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Install Python packages
        run: |
          pip install cryptography
          pip install httplib2

      - name: Wget required files
        run: |
          npm install
          wget https://raw.githubusercontent.com/ballerina-platform/${{ github.event.client_payload.repoName }}/master/.github/CODEOWNERS
          python3 dependabot/notify_failure.py ${{ github.event.client_payload.repoName }}
        env:
          ENV_NOTIFICATIONS_CHAT_ID: ${{secrets.NOTIFICATIONS_CHAT_ID}}
          ENV_NOTIFICATIONS_CHAT_KEY: ${{secrets.NOTIFICATIONS_CHAT_KEY}}
          ENV_NOTIFICATIONS_CHAT_TOKEN: ${{secrets.NOTIFICATIONS_CHAT_TOKEN}}
          ENV_USER_ENCRYPTION_KEY: ${{secrets.USER_ENCRYPTION_KEY}}
